### ISSUE TITLE
Invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by gessgallardo** [woolf/active_workbench#2]
He guys I got this error while building on my rails 4.0.0:

```
ERROR:  While executing gem ... (ArgumentError)
    invalid byte sequence in US-ASCII
```

So I do some research and find this workaround:

```
if RUBY_VERSION =~ /1.9/
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end
```

it's supposed to be added at top of the Gemfile, I think you should added on your gemfile so it will be available for anyone.

all credit to alanho(alanho.com)[http://www.a.rnaud.net/2011/10/how-to-fix-invalid-byte-sequence-in-us-ascii-in-bundler-installation/]

Have a nice day and nice project guys :)!

**Comment by kinduff** [comment]
:+1:
